name: build

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.svg', '**.md' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: '3.12'

    - name: Run Python unit tests
      run: |
        python3 -u -m unittest tests/tests.py
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Verify that the Docker image for the action builds
      run: docker build . --file Dockerfile

    - name: Integration test
      id: integration
      uses: ./
      with:
        colors: dark
        commit-and-push: false
        featured-repository: Chips-n-Salsa
        animated-language-chart: true
        locale: en
        #fail-on-error: false
        #category-order: general, repositories, languages, contributions
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Output the outputs of the integration test of the action
      env:
        EXIT_CODE: ${{ steps.integration.outputs.exit-code }}
      run: |
        echo "exit-code = $EXIT_CODE"

    - name: Upload generated SVG as a workflow artifact for inspection if necessary
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: generated-image
        path: images/userstats.svg
